function gemius_pending(e){window[e]=window[e]||function(){var g=window[e+"_pdata"]=window[e+"_pdata"]||[];g[g.length]=Array.prototype.slice.call(arguments,0)}}(function(e){for(var g;g=e.pop();)gemius_pending(g)})("gemius_cmd gemius_hit gemius_event gemius_init pp_gemius_hit pp_gemius_event pp_gemius_init".split(" "));window.pp_gemius_cmd=window.pp_gemius_cmd||window.gemius_cmd;var GemiusPlayerVersion=300;
if("undefined"==typeof GemiusPlayerVisibility){var GemiusPlayerVisibility={isframe:null,framevis:null,childs:[],timerID:null,init:function(){try{GemiusPlayerVisibility.isframe=top!==self,window.addEventListener?window.addEventListener("message",GemiusPlayerVisibility._msgreceive,!1):window.attachEvent&&window.attachEvent("onmessage",GemiusPlayerVisibility._msgreceive),GemiusPlayerVisibility.isframe&&parent.postMessage("__xx_gplayer_vischeck_xx__","*")}catch(e){}},check:function(e){try{return GemiusPlayerVisibility.isframe&&
null===GemiusPlayerVisibility.framevis?(parent.postMessage("__xx_gplayer_vischeck_xx__","*"),null):GemiusPlayerVisibility.isframe&&!1===GemiusPlayerVisibility.framevis?!1:null!==GemiusPlayerVisibility.isframe?GemiusPlayerVisibility._inScreen(e):null}catch(g){return null}},_msgreceive:function(e){if("string"==typeof e.data&&"__xx_gplayer_vischeck_xx__"==e.data)try{GemiusPlayerVisibility.isframe&&null===GemiusPlayerVisibility.framevis&&parent.postMessage("__xx_gplayer_vischeck_xx__","*");var g=document.getElementsByTagName("iframe"),
h=null;try{for(var a=0;a<g.length;a++)if(g[a].contentWindow===e.source){h=g[a];break}}catch(c){}for(a=0;a<g.length;a++)if(null===h||g[a]==h){e=!1;for(var b=0;b<GemiusPlayerVisibility.childs.length;b++)if(g[a]===GemiusPlayerVisibility.childs[b].frame){e=!0;break}e||(GemiusPlayerVisibility.childs[GemiusPlayerVisibility.childs.length]={frame:g[a],vis:null})}GemiusPlayerVisibility.timerID||(GemiusPlayerVisibility.timerID=setInterval(GemiusPlayerVisibility._notify,1E3))}catch(c){}else"string"==typeof e.data&&
"__xx_gplayer_visibility_xx__/"==e.data.substr(0,29)&&(GemiusPlayerVisibility.framevis="true"==e.data.substr(29))},_notify:function(e){try{if(!1===GemiusPlayerVisibility.isframe||null!==GemiusPlayerVisibility.framevis)for(e=0;e<GemiusPlayerVisibility.childs.length;e++){var g=(!GemiusPlayerVisibility.isframe||GemiusPlayerVisibility.framevis)&&GemiusPlayerVisibility._inScreen(GemiusPlayerVisibility.childs[e].frame);if(GemiusPlayerVisibility.childs[e].vis!==g){var h="__xx_gplayer_visibility_xx__/"+(g?
"true":"false");GemiusPlayerVisibility.childs[e].vis=g;GemiusPlayerVisibility.childs[e].frame.contentWindow.postMessage(h,"*")}}}catch(a){}},_inScreen:function(e){if(e){for(var g=["webkitFullscreenElement","mozFullScreenElement","msFullscreenElement"],h=null,a=0;a<g.length;a++)document[g[a]]&&(h=document[g[a]]);if(h)return h==e||GemiusPlayerVisibility._isChild(h,e);if("visible"!=document.visibilityState)return!1;e=e.getBoundingClientRect();g=Math.min(window.innerHeight,e.top+e.height)-Math.max(e.top,
0);h=Math.min(window.innerWidth,e.left+e.width)-Math.max(e.left,0);return 0<h&&0<g&&(h*g>e.height*e.width*.5||h*g>window.innerHeight*window.innerWidth*.5)}return null},_isChild:function(e,g){for(var h=g.parentNode;null!=h;){if(h==e)return!0;h=h.parentNode}return!1}};GemiusPlayerVisibility.init()}
function GemiusPlayer(e,g,h){this.interval=300;this.updateInterval=1;this.instanceID=((new Date).getTime()+Math.floor(1E3*Math.random())).toString();this.playerID=e;this.gemiusID=g;this.playerData=h||{};this.disposed=this.initialized=!1;this.programs={};this.ads={};this.hitsCounter=0;this.pageshowFun=this.pagehideFun=this.unloadFun=this.updateIntervalID=this.continueIntervalID=this.hidetime=this.visible=this.resolution=this.videoObject=this.currentProgramID=null;this._playerDataKeys={currentDomain:"_SPD",
resolution:"_SPR",volume:"_SPV"};this._playerInnerDataKeys={ctvApplicationLabel:"_app_label"};this._programDataKeys={programType:"_SCTE",programDuration:"_SCD",programTransmission:"_SCTR",programName:"_SCT",series:"_SCS",typology:"_SCTY",premiereDate:"_SCPD",externalPremiereDate:"_SCEPD",quality:"_SCQ",resolution:"_SCR",volume:"_SCV",programGenre:"_SCG",programPartialName:"_SCPN",programProducer:"_SCPP",programThematicCategory:"_SCTC",programSeason:"_SCSS",transmissionChannel:"_SCTB",transmissionStartTime:"_SCTS",
transmissionType:"_SCTT"};this._programExtraDataKeys={partID:"_SCP"};this._adDataKeys={adName:"_SAN",adDuration:"_SAD",adTransmission:"_SATR",adType:"_SAT",campaignClassification:"_SAC",quality:"_SAQ",resolution:"_SAR",volume:"_SAV",adFormat:"_SAF"};this._adExtraDataKeys={adPosition:"_SAP",breakSize:"_SBS",breakType:"_SBT"};this._eventDataKeys={listID:"_SL"};this._reservedDataKeys={autoPlay:!0};this.setVideoObject=function(a){this.videoObject=a};this.newProgram=function(a,b){this._init();this.programs[a]=
{state:"new",started:!1,program_started:!1,last_action_time:null,data:this._clone(b),extradata:{}};this._validateParams(this.programs[a].data);this._sendHit(a,null,"data","streamcontent",[])};this.newAd=function(a,b){this._init();this.ads[a]={state:"new",started:!1,last_action_time:null,currentProgramID:null,currentAdPosition:null,data:this._clone(b),extradata:{}};this._validateParams(this.ads[a].data);this._sendHit(null,a,"data","streamspot",[])};this.programEvent=function(a,b,c,d){d=d||{};this.programs[a]&&
(this._updateCustomProgramData(a,d),this.hitsCounter=a==this.currentProgramID?this.hitsCounter+1:1,this.currentProgramID=a,2E3>=this.hitsCounter?"play"==c?this._playProgram(a,b,d):"chngQual"==c||"chngRes"==c||"chngVol"==c?this._changeParam(a,null,b,c,d):this._event(a,null,b,c,d):this._stopAll())};this.adEvent=function(a,b,c,d,f){f=f||{};this.programs[a]&&this.ads[b]&&(this._updateCustomAdData(b,f),this.hitsCounter=a==this.currentProgramID?this.hitsCounter+1:1,this.currentProgramID=a,2E3>=this.hitsCounter?
"play"==d?this._playAd(a,b,c,f):"chngQual"==d||"chngRes"==d||"chngVol"==d?this._changeParam(a,b,c,d,f):this._event(a,b,c,d,f):this._stopAll())};this.dispose=function(){this._dispose()};this._playProgram=function(a,b,c){this._stopAll();var d=0==this.programs[a].program_started?"programstart":this.programs[a].started?"play":"start";b=["_SCO="+b,"_SED="+this._updateActionTime(this.programs[a])];"undefined"!=typeof c.autoPlay&&(b=b.concat(["_ECA="+(c.autoPlay?1:0)]));"undefined"!=typeof c.partID?this.programs[a].extradata.partID=
c.partID:delete this.programs[a].extradata.partID;"undefined"!=typeof c.volume&&(b=b.concat(["_SPVN="+c.volume]));"undefined"!=typeof c.resolution&&(b=b.concat(["_SPRN="+c.resolution]));this.programs[a].state="play";this.programs[a].started=!0;this.programs[a].program_started=!0;this._sendHit(a,null,"stream",d,b);"undefined"!=typeof c.volume&&(this.playerData.volume=c.volume);"undefined"!=typeof c.resolution&&(this.playerData.resolution=c.resolution);for(var f in this.ads)this.ads[f].started=!1;for(var k in this.programs)k!=
a&&(this.programs[k].started=!1,this.programs[k].program_started=!1)};this._playAd=function(a,b,c,d){this._stopAll();var f=!this.ads[b].started||this.ads[b].currentProgramID!=a||this.ads[b].currentAdPosition!=d.adPosition,k=this._getBreakType(a,c);f=f&&"post"!=k&&0==this.programs[a].program_started?"programstart":f?"start":"play";c=["_SCO="+c,"_SED="+this._updateActionTime(this.ads[b])];"undefined"!=typeof d.autoPlay&&(c=c.concat(["_ECA="+(d.autoPlay?1:0)]));"undefined"!=typeof d.adPosition?this.ads[b].extradata.adPosition=
d.adPosition:delete this.ads[b].extradata.adPosition;"undefined"!=typeof d.breakSize?this.ads[b].extradata.breakSize=d.breakSize:delete this.ads[b].extradata.breakSize;k?this.ads[b].extradata.breakType=k:delete this.ads[b].extradata.breakType;"undefined"!=typeof d.volume&&(c=c.concat(["_SPVN="+d.volume]));"undefined"!=typeof d.resolution&&(c=c.concat(["_SPRN="+d.resolution]));this.ads[b].state="play";this.ads[b].started=!0;this.ads[b].currentProgramID=a;this.ads[b].currentAdPosition=d.adPosition;
"post"!=k&&(this.programs[a].program_started=!0);this._sendHit(a,b,"stream",f,c);"undefined"!=typeof d.volume&&(this.playerData.volume=d.volume);"undefined"!=typeof d.resolution&&(this.playerData.resolution=d.resolution)};this._event=function(a,b,c,d,f){var k={pause:"pause",stop:"stop",close:"close",buffer:"buffering","break":"break",seek:"seek",complete:"complete",skip:"skip",next:"next",prev:"prev"},l=b?this.ads[b]:this.programs[a];if(k[d]){f=["_SED="+this._updateActionTime(l)].concat(this._convertEventParams(f));
"undefined"!=typeof c&&(f=f.concat(["_SCO="+c]));if("stop"==d||"complete"==d||"close"==d)l.started=!1,b||(this.programs[a].program_started=!1);l.state=k[d];this._sendHit(a,b,"stream",k[d],f)}};this._changeParam=function(a,b,c,d,f){d=b?this.ads[b]:this.programs[a];var k=["_SED="+this._updateActionTime(d)];"undefined"!=typeof c&&(k=k.concat(["_SCO="+c]));"undefined"!=typeof f.volume&&(k=k.concat(["_SPVN="+f.volume]));"undefined"!=typeof f.resolution&&(k=k.concat(["_SPRN="+f.resolution]));"undefined"!=
typeof f.quality&&(k=k.concat([(b?"_SAQN=":"_SCQN=")+f.quality]));this._sendHit(a,b,"stream","continue",k);f.quality&&(d.data.quality=f.quality);f.resolution&&(this.playerData.resolution=f.resolution);f.volume&&(this.playerData.volume=f.volume)};this._getBreakType=function(a,b){try{var c=this.programs[a].data.programDuration||0,d=this.programs[a].data.transmissionType||0;"number"!=typeof c&&(c=parseInt(c,10));"number"!=typeof d&&(d=parseInt(d,10));"number"!=typeof b&&(b=parseInt(b,10));return 2==
d?"live":0>c?"unknown":100>=c&&0>=b||100<c&&5>b?"pre":0<c&&(100>=c&&b>=c||100<c&&b>c-5)?"post":"mid"}catch(f){return""}};this._stopAll=function(){for(var a in this.programs)"play"==this.programs[a].state&&this._event(a,null,void 0,"pause",{});for(var b in this.ads)"play"==this.ads[b].state&&this.programs[this.ads[b].currentProgramID]&&this._event(this.ads[b].currentProgramID,b,void 0,"pause",{})};this._update=function(){var a=GemiusPlayerVisibility.check(this.videoObject),b=this._getPlayerSize();
if(a!==this.visible||b!==this.resolution)this._continue(),this.visible=a,this.resolution=b};this._getPlayerSize=function(){if(this.videoObject)try{var a=this.videoObject.getBoundingClientRect();return parseInt(a.width,10)+"x"+parseInt(a.height,10)}catch(b){return null}else return null};this._continue=function(){for(var a in this.programs)if("play"==this.programs[a].state){var b=["_SED="+this._updateActionTime(this.programs[a])];this._sendHit(a,null,"stream","continue",b)}for(var c in this.ads)"play"==
this.ads[c].state&&(b=["_SED="+this._updateActionTime(this.ads[c])],this._sendHit(this.ads[c].currentProgramID,c,"stream","continue",b))};this._sendClosingHits=function(a){try{"function"==typeof gemius_close&&gemius_close();var b=!1,c;for(c in this.programs)if("play"==this.programs[c].state){var d=["_SED="+this._updateActionTime(this.programs[c])];this._sendHit(c,null,"stream",a,d);b=!0}for(var f in this.ads)"play"==this.ads[f].state&&(d=["_SED="+this._updateActionTime(this.ads[f])],this._sendHit(this.ads[f].currentProgramID,
f,"stream",a,d),b=!0);if(b&&"function"!=typeof navigator.sendBeacon)for(var k=(new Date).getTime();k+250>(new Date).getTime(););}catch(l){}};this._unload=function(){this._sendClosingHits("unload")};this._pagehide=function(){this._unload();null==this.hidetime&&(this.hidetime=(new Date).getTime())};this._pageshow=function(){if(null!=this.hidetime){var a=(new Date).getTime();a=a>this.hidetime?a-this.hidetime:0;try{for(var b in this.programs)this._updateHideTime(this.programs[b],a);for(var c in this.ads)this._updateHideTime(this.ads[c],
a)}catch(d){}this.hidetime=null}};this._updateHideTime=function(a,b){try{"play"==a.state&&a.last_action_time&&(a.last_action_time+=b)}catch(c){}};this._updateActionTime=function(a){var b=0;try{"play"==a.state&&a.last_action_time&&(b=Math.round(((new Date).getTime()-a.last_action_time)/1E3),0>b||b>2*this.interval)&&(b=0),a.last_action_time=(new Date).getTime()}catch(c){}return b};this._sendHit=function(a,b,c,d,f){this.disposed||(a=["_EC="+d].concat(this._getPlayerParams()).concat(this._getProgramParams(a)).concat(this._getAdParams(b)).concat(f),
(b=this._getPlayerInnerParams())&&0<b.length?gemius_cmd("event",{type:c,id:this.gemiusID,extra:a,inner:b}):gemius_event.apply(window,["_"+c+"_",this.gemiusID].concat(a)))};this._getProgramParams=function(a){if(!this.programs[a])return[];var b=["_SC="+a];b=b.concat(this._convertParams(this.programs[a].data,this._programDataKeys,!0));return b=b.concat(this._convertParams(this.programs[a].extradata,this._programExtraDataKeys))};this._getAdParams=function(a){if(!this.ads[a])return[];var b=["_SA="+a];
b=b.concat(this._convertParams(this.ads[a].data,this._adDataKeys,!0));return b=b.concat(this._convertParams(this.ads[a].extradata,this._adExtraDataKeys))};this._getPlayerParams=function(){var a=["_SPI="+this.instanceID,"_SP="+this.playerID];null!==this.resolution&&(a=a.concat(["_SPS="+this.resolution]));null!==this.visible&&(a=a.concat(["_SPIS="+(this.visible?"1":"0")]));return a.concat(this._convertParams(this.playerData,this._playerDataKeys))};this._getPlayerInnerParams=function(){return this._convertParams(this.playerData,
this._playerInnerDataKeys)};this._validateParams=function(a){var b={programDuration:1,adDuration:1},c={programTransmission:20,adTransmission:20,programPartialName:64,programProducer:64,programSeason:64,transmissionChannel:64,transmissionStartTime:10};if("undefined"!=typeof a)for(var d in a)c[d]&&("string"==typeof a[d]?a[d]=a[d].substr(0,c[d]):delete a[d]),b[d]&&(a[d]=parseInt(a[d]))};this._convertEventParams=function(a){return this._convertParams(a,this._eventDataKeys)};this._convertParams=function(a,
b,c){var d=[];if("undefined"!=typeof a)for(var f in a)if(b[f]||c)d[d.length]=(b[f]||f)+"="+a[f];return d};this._updateCustomProgramData=function(a,b){for(var c in b)c in this._reservedDataKeys||(this.programs[a].data[c]=b[c]);this._validateParams(this.programs[a].data)};this._updateCustomAdData=function(a,b){for(var c in b)c in this._reservedDataKeys||(this.ads[a].data[c]=b[c]);this._validateParams(this.ads[a].data)};this._assignDataKeys=function(a,b){for(var c in b)a[c]=!0};this._initReservedKeys=
function(){this._assignDataKeys(this._reservedDataKeys,this._playerDataKeys);this._assignDataKeys(this._reservedDataKeys,this._programDataKeys);this._assignDataKeys(this._reservedDataKeys,this._programExtraDataKeys);this._assignDataKeys(this._reservedDataKeys,this._adDataKeys);this._assignDataKeys(this._reservedDataKeys,this._adExtraDataKeys);this._assignDataKeys(this._reservedDataKeys,this._eventDataKeys);delete this._reservedDataKeys.programDuration;delete this._reservedDataKeys.adDuration};this._addEvent=
function(a,b,c){a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent&&a.attachEvent("on"+b,c)};this._removeEvent=function(a,b,c){a.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)};this._init=function(){if(!this.initialized&&!this.disposed){this.initialized=!0;this._initReservedKeys();this._update();this.continueIntervalID=setInterval(this._wrapFun(this,"_continue"),1E3*this.interval);this.updateIntervalID=setInterval(this._wrapFun(this,"_update"),1E3*
this.updateInterval);this.unloadFun=this._wrapFun(this,"_unload");this.pagehideFun=this._wrapFun(this,"_pagehide");this.pageshowFun=this._wrapFun(this,"_pageshow");try{"onpagehide"in window?(this._addEvent(window.top,"pagehide",this.pagehideFun),this._addEvent(window.top,"pageshow",this.pageshowFun)):"function"==typeof navigator.sendBeacon?this._addEvent(window.top,"unload",this.unloadFun):this._addEvent(window.top,"beforeunload",this.unloadFun)}catch(a){"onpagehide"in window?(this._addEvent(window,
"pagehide",this.pagehideFun),this._addEvent(window,"pageshow",this.pageshowFun)):"function"==typeof navigator.sendBeacon?this._addEvent(window,"unload",this.unloadFun):this._addEvent(window,"beforeunload",this.unloadFun)}}};this._dispose=function(){if(this.initialized&&!this.disposed){this._sendClosingHits("dispose");clearInterval(this.continueIntervalID);clearInterval(this.updateIntervalID);try{"onpagehide"in window?(this._removeEvent(window.top,"pagehide",this.pagehideFun),this._removeEvent(window.top,
"pageshow",this.pageshowFun)):"function"==typeof navigator.sendBeacon?this._removeEvent(window.top,"unload",this.unloadFun):this._removeEvent(window.top,"beforeunload",this.unloadFun)}catch(a){"onpagehide"in window?(this._removeEvent(window,"pagehide",this.pagehideFun),this._removeEvent(window,"pageshow",this.pageshowFun)):"function"==typeof navigator.sendBeacon?this._removeEvent(window,"unload",this.unloadFun):this._removeEvent(window,"beforeunload",this.unloadFun)}this.disposed=!0}};this._wrapFun=
function(a,b){return function(){a[b]()}};this._clone=function(a){var b={};if(!a)return b;for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}}
if("undefined"!=typeof window.gemius_player_data){for(var i=0;i<window.gemius_player_data.length;i++){var data=window.gemius_player_data[i],obj=data[0],fun=data[1],args=data[2];if("GemiusPlayer"!=fun)obj[fun].apply(obj,args);else{var nobj=new function(){return GemiusPlayer.apply(this,args)},attrname;for(attrname in nobj)obj[attrname]=nobj[attrname]}}window.gemius_player_data=[]}
(function(e,g){try{var h=e.createElement(g),a=e.getElementsByTagName(g)[0],b="http"+("https:"==location.protocol?"s":"");h.async="true";h.defer="true";h.src=b+"://tvn.hit.gemius.pl/gemiuslib.js&v="+GemiusPlayerVersion;a.parentNode.insertBefore(h,a)}catch(c){}})(document,"script");
//# sourceMappingURL=gplayer.min.js.map
